services:
  bot:
    image: ghcr.io/mastodon.de/greetingbot
    container_name: GreetingBot
    environment:
      # NTFY Topic Link (json)
      - NTFY=""
      # The Mastodon Instance
      - INSTANCE=""
      # The Personal Access Token
      - PAT=""
      